---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3004161963-21DknbCQW7sDyyMfmsHuZO4jnS541IL5OkNkICE
:access_token_secret: JBXgbp0alP9ypYQgr9wnj5eP61cGahxBfcxcOb7OUzZAg
